---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porthole-readonly
  namespace: team-a
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/part-of: porthole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: porthole-readonly
subjects:
- kind: ServiceAccount
  name: porthole
  namespace: porthole
