---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterRole.porthole-readonly.yaml
- deployment.porthole.yaml
- namespace.porthole.yaml
- networkPolicy.porthole.yaml
- service.porthole.yaml
- serviceAccount.porthole.yaml
