---
# Bind this role in namespaces that opt into Secret/ConfigMap key-name metadata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porthole-readonly-with-secrets
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/part-of: porthole
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      aggregate-to-porthole-readonly-with-secrets: "true"
rules: []
